sudo: false
language: julia
julia:
  - "1.0"
  - "1.1"
  - "1.2"
  - "1.3"
  - "1.4"
  - "1.5"
  - "nightly"
matrix:
  allow_failures:
    - julia: "nightly"
  fast_finish: true
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - set -ev
  - julia -e 'using InteractiveUtils; using Pkg; versioninfo(); Pkg.build("ROCAnalysis")'
  - xvfb-run julia --check-bounds=yes -e 'using Pkg; Pkg.test("ROCAnalysis", coverage=true)'
